development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://h:p302170cc45b53ea282ad6ffd6aaa2c4ae2773f789b501e3eb2142004077ca460@ec2-54-197-118-201.compute-1.amazonaws.com:19489
  channel_prefix: app1_production
